#+title: Cafés
#+date: <2021-05-05 23:52>
#+filetags: coffee

I go to cafes often and want to record down my experience, so that I can leave a trail of credible, organic reviews for these places.
So that reviews for these places aren't just dominated by professional bloggers' sites which are SEO-ed to death.

I rate these cafes commensurate with their prices. I don't expect single-origin coffee from the neighborhood
/kopi-tiam/, but I also believe that Starbucks coffee is way overpriced. Of course, the coffee merely forms part of the cafe experience among other factors,
such as the atmosphere and the food, so I try to keep those in mind too.

My scale is out of 5:
 - 3 is at expectation,
 - 2 and 4 are below and above respectively, and
 - 1 and 5 are way below and way above respectively.

* Kurasu
  - Visited in May 2021. Tried the Ethopian pour over. It's alright; nice clean taste, but not much else.
  - The cafe has a nice aesthetic, except that the outward view is kinda terrible due to ongoing construction outside.
  - 3/5, since it was priced relatively higher at $8.

* Glasshouse
  - Visited in May 2021. I spotted Nylon beans, but I'm not sure which ones they used specifically.
  - Nice ambience, but CHIMES is just nice in general.
  - I had the long black for $5. Nothing particularly special.
  - 3/5
